name: Update-ip

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches:
      - master
  schedule:
    - cron: "7 0 * * *"
  watch:
    types: [started]

jobs:
  update-ip-job:
    runs-on: ubuntu-latest  # 1. 使用 ubuntu-latest
    steps:
      - name: Install dependencies  # 2. 安装 curl、git、jq、bash 命令
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git jq bash

      - name: Clone repository   # 3. 从当前仓库克隆代码
        uses: actions/checkout@v4

      - name: Run daily.sh  # 4. 进入克隆的仓库里，运行 bash script1.sh 并等待 1 秒
        run: |
          bash daily.sh --add-country HK JP SG CA GB FR FI PL DE SE
          sleep 1

      - name: remove files   # 6. 移除多余文件
        run: rm -rf daily.sh .github

      - name: Push to dat branch  # 7. 将当前目录上传到当前仓库的 dat 分支
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B dat
          git add .
          git commit -m "Update" || echo "No changes to commit"
          git push origin dat -f
